baseurl = "https://gandreadis.com"
title = "Georgios Andreadis"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true

[params]
  author = "Georgios Andreadis"
  info = ["Conductor","PhD Candidate"]
  description = "Personal website of Georgios Andreadis"
  keywords = "georgios,andreadis,gandreadis,jorgos,image registration"
  avatarurl = "images/directie-klassiek-collectief-fotograaf-kang-li.jpg" #"images/gandreadis-avatar.jpg"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  footercontent = "<em>Photography: Kang Li</em>"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:info@gandreadis.com"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/gandreadis"
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 3
  url = "https://github.com/gandreadis/"
[[params.social]]
  name = "ResearchGate"
  icon = "fa fa-researchgate fa-2x"
  weight = 4
  url = "https://www.researchgate.net/profile/Georgios_Andreadis4"
[[params.social]]
  name = "StackOverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 5
  url = "https://stackoverflow.com/users/975317/gandreadis"

# Menu links
[[menu.main]]
  name = "Music"
  weight = 1
  url = "music/"
[[menu.main]]
  name = "Research"
  weight = 2
  url = "research/"
